version: '3.8'

volumes:
  mysql_data:
    driver: local

services:
  db:
    image: mysql:8.0
    container_name: dbtest
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Teste@123"
      MYSQL_PASSWORD: "Teste@123"
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    expose:
      - 3307